package com.cabgo.enums;

public enum ConversationState {
    IDLE,
    MAIN_MENU,
    AWAITING_PICKUP,
    AWAITING_DROP,
    AWAITING_VEHICLE_SELECTION,
    AWAITING_CONFIRMATION,
    RIDE_ACTIVE,
    AWAITING_CANCEL_CONFIRM,
    AWAITING_PAYMENT_METHOD,
    AWAITING_RATING,
    SUPPORT,
    
    // Driver registration states
    DRIVER_REG_NAME,
    DRIVER_REG_EMAIL,
    DRIVER_REG_CITY,
    DRIVER_REG_VEHICLE_CATEGORY,
    DRIVER_REG_VEHICLE_MODEL,
    DRIVER_REG_VEHICLE_NUMBER,
    DRIVER_REG_VEHICLE_COLOR,
    DRIVER_REG_AADHAAR,
    DRIVER_REG_LICENSE,
    DRIVER_REG_DOC_SELFIE,
    DRIVER_REG_DOC_AADHAAR,
    DRIVER_REG_DOC_LICENSE,
    DRIVER_REG_DOC_RC,
    DRIVER_REG_DOC_VEHICLE,
    
    // Fare estimation states
    FARE_EST_PICKUP,
    FARE_EST_DROP,
    FARE_EST_VEHICLE
}

